name: test

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  tests:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: ["12.x", "14.x"]

    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Node v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Install dependencies"
      - run: npm install

      - name: "Run tests"
      - run: npm run test:ci

      - name: Codecov
      - uses: codecov/codecov-action@v1

      - name: Build
      - run: npm run build
